# frozen_string_literal: true

source 'https://www.rubygems.org'

gem 'cucumber', '~> 2.0'
gem 'parallel_tests', '~> 2.16.0'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rspec'
gem 'sauce_whisk'
gem 'watir'
