# frozen_string_literal: true

source 'https://www.rubygems.org'

gem 'cucumber'
gem 'parallel_tests'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rspec'
gem 'simple_sauce', '~> 1.0.0.pre.alpha'
gem 'watir'
