# frozen_string_literal: true

source 'https://www.rubygems.org'

gem 'capybara', '>= 3.16.2'
gem 'parallel_split_test'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rspec', '~>1.32'
gem 'sauce_whisk'
gem 'simple_sauce', '~> 1.0.0.pre.alpha.1'
