# frozen_string_literal: true

source 'https://rubygems.org'

gem 'parallel_split_test'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rspec', '~>1.32'
gem 'sauce_whisk'
gem 'watir', '= 7.0.0.beta5'
gem 'selenium-webdriver', '= 4.0.0.rc2'
