# frozen_string_literal: true

require 'rspec/core/rake_task'
require 'rubocop/rake_task'

RuboCop::RakeTask.new(:rubocop) do |t|
  t.options = ['--display-cop-names']
end

#
# For use in building a unique Build Name for running tests in parallel on Sauce Labs from a local machine
#
ENV['SAUCE_BUILD_NAME'] = "Ruby-RSpec-Capybara: Local-#{Time.now.to_i}"

#
# Uses parallel-split-test gem to set the number of tests that get run in parallel
# parallel_split_test gem splits up tests within files
# Typically this gets set up to the limit of your Sauce Labs Sessions,
# or a subset as required to run multiple builds on Sauce Labs simultaneously
#
ENV['PARALLEL_SPLIT_TEST_PROCESSES'] ||= '10'

#
# Ideally run one of these Rake Tasks per build in your CI
#
# Ideally pull these values from a config file instead of hard-coding
#
desc 'Run tests in parallel within suite using Windows 10 with Edge'
task :windows_10_edge do
  ENV['PLATFORM_NAME'] = 'Windows 10'
  ENV['BROWSER_NAME'] = 'edge'
  system 'parallel_split_test spec'
end

desc 'Run tests in parallel within suite using Mac Sierra with Chrome'
task :mac_sierra_chrome do
  ENV['PLATFORM_NAME'] = 'macOS 10.12'
  ENV['BROWSER_NAME'] = 'chrome'
  system 'parallel_split_test spec'
end

desc 'Run tests in parallel within suite using Windows 7 with Firefox'
task :windows_7_ff do
  ENV['PLATFORM_NAME'] = 'Windows 7'
  ENV['BROWSER_NAME'] = 'firefox'
  system 'parallel_split_test spec'
end

desc 'Run tests in parallel within suite using Windows 8 with Internet Explorer'
task :windows_8_ie do
  ENV['PLATFORM_NAME'] = 'Windows 8.1'
  ENV['BROWSER_NAME'] = 'ie'
  system 'parallel_split_test spec'
end

desc 'Run tests in parallel within suite using Mac Mojave with Safari'
task :mac_mojave_safari do
  ENV['PLATFORM_NAME'] = 'macOS 10.14'
  ENV['BROWSER_NAME'] = 'safari'
  system 'parallel_split_test spec'
end

desc 'Run tests in parallel within suite using Mac Mojave with Safari'
task :headless do
  ENV['BROWSER_NAME'] = 'chrome'
  ENV['PLATFORM_NAME'] = 'linux'
  system 'parallel_split_test spec'
end

#
# Always set a Default Task
#
task :default do
  Rake::Task[:mac_sierra_chrome].execute
end

#
# For Running Sauce Demo
# This runs multiple platforms at the same time, which isn't considered best practice,
# but is useful for demonstrating Sauce Labs features
#

@success = true

PLATFORMS = %w[windows_10_edge mac_sierra_chrome windows_7_ff windows_8_ie mac_mojave_safari].freeze

PLATFORMS.each do |platform|
  task "#{platform}_demo" do
    ENV['PLATFORM'] = platform
    begin
      @result = system 'parallel_split_test spec'
    ensure
      @success &= @result
    end
  end
end

desc 'Sauce Labs Demo to run multiple platforms simultaneously'
multitask sauce_demo: PLATFORMS.map { |p| "#{p}_demo" } do
  raise StandardError, 'Tests failed!' unless @success
ensure
  @success &= @result
end
