name: Sauce Examples

on:
  - push
  - pull_request

jobs:
  ruby-tests:
    name: Sauce Examples
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: [ accessibility, visual ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install Dependencies
        working-directory: sauce-features/${{ matrix.dir }}
        run: bundle install
      - name: Run ${{ matrix.dir }} tests
        working-directory: sauce-features/${{ matrix.dir }}
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: bundle exec rake
